# Configuration for code assist and review settings

# Code Quality Settings
code_quality:
  max_pr_size: 500
  max_files_changed: 50
  require_tests: true
  require_documentation: true

# Supported Languages
languages:
  - javascript
  - java
  - python
  - ruby
  - go
  - rust
  - php
  - shell

# Security Settings
security:
  scan_dependencies: true
  scan_code: true
  scan_secrets: true
  fail_on_high_severity: true

# Testing Configuration
testing:
  parallel_jobs: 3
  timeout_minutes: 30
  coverage_threshold: 80

# Deployment Settings
deployment:
  staging:
    auto_deploy: true
    require_approval: false
  production:
    auto_deploy: false
    require_approval: true
    approvers:
      - maintainers
      - admin

# Notification Settings
notifications:
  slack_webhook: ""
  email_notifications: true
  github_notifications: true